<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .info {
            margin-bottom: 15px;
            font-size: 9px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
            font-size: 8px;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
            color: #333;
        }
        .status {
            padding: 2px 4px;
            border-radius: 3px;
            font-size: 7px;
            font-weight: bold;
        }
        .status-pending { background-color: #fff3cd; color: #856404; }
        .status-approved { background-color: #d1e7dd; color: #0f5132; }
        .status-rejected { background-color: #f8d7da; color: #721c24; }
        .status-paid { background-color: #d1e7dd; color: #0f5132; }
        .price { font-weight: bold; color: #28a745; }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="info">
            Generated on: {{ $generated_at }} | Total Records: {{ $total_count }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 15%;">Service</th>
                <th style="width: 12%;">Professional</th>
                <th style="width: 12%;">Customer</th>
                <th style="width: 8%;">Price</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 8%;">Payment</th>
                <th style="width: 8%;">Consulting</th>
                <th style="width: 9%;">Delivery</th>
                <th style="width: 8%;">Created</th>
                <th style="width: 7%;">Negotiation</th>
            </tr>
        </thead>
        <tbody>
            @foreach($services as $service)
            <tr>
                <td>{{ $service->id }}</td>
                <td>{{ Str::limit($service->service_name, 20) }}</td>
                <td>{{ Str::limit($service->professional->name ?? 'N/A', 15) }}</td>
                <td>{{ Str::limit($service->user->name ?? 'N/A', 15) }}</td>
                <td class="price">₹{{ number_format($service->final_price, 0) }}</td>
                <td>
                    <span class="status status-{{ $service->admin_status }}">
                        {{ ucfirst($service->admin_status) }}
                    </span>
                </td>
                <td>
                    <span class="status status-{{ $service->payment_status }}">
                        {{ ucfirst($service->payment_status) }}
                    </span>
                </td>
                <td>{{ ucfirst(str_replace('_', ' ', $service->consulting_status)) }}</td>
                <td>
                    @if($service->delivery_date)
                        {{ \Carbon\Carbon::parse($service->delivery_date)->format('d/m/Y') }}
                    @else
                        Not Set
                    @endif
                </td>
                <td>{{ $service->created_at->format('d/m/Y') }}</td>
                <td>{{ $service->negotiation_status !== 'none' ? 'Yes' : 'No' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Additional Services Management Report - Generated by Admin Panel
    </div>
</body>
</html>